apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu
  namespace: esd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: menu
  template:
    metadata:
      labels:
        app: menu
    spec:
      containers:
      - name: menu-container
        image: asia-southeast1-docker.pkg.dev/findmyfood-455107/my-repo/menu:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        volumeMounts:
        - name: firebase-creds
          mountPath: /app/firebase_credentials.json
          subPath: firebase_credentials.json
      volumes:
      - name: firebase-creds
        secret:
          secretName: menu-firebase-secret
